import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import { Navbar } from "@/components/navbar";

const jetbrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "DevRoast",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={jetbrainsMono.variable}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
